

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.*;
import javax.swing.*;
import java.awt.*;
import java.awt.Event;
import java.awt.event.KeyEvent;
/**
 *
 * @author Reed
 */
public class Changelog extends javax.swing.JDialog {
    private String CHLG;
    private StringBuilder egg;
    /**
     * Creates new form Changelog
     */
    public Changelog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jButton3.setVisible(false);
        inicializar();
        CHLG = "ADMIN"; //Huevo de pascua que sirve para editar el ChangeLog
        egg = new StringBuilder();
    }
    private void inicializar(){
        try{
            //Leemos el txt en formato Unicode
            FileInputStream in = new FileInputStream(System.getProperty("user.home") + "\\AppData\\Roaming\\.minecraft\\mods\\CHLog.txt");
            InputStreamReader isr = new InputStreamReader (in, "UTF8");
            BufferedReader bf = new BufferedReader (isr);
            String temp;
            jTextArea1.append(bf.readLine());
            while ((temp = bf.readLine()) != null){
                jTextArea1.append("\n");
                jTextArea1.append(temp);
            }
            in.close();
            isr.close();
            bf.close();
            jButton1.setEnabled(true);
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, "Error al abrir el ChangeLog.");
            File error = new File (System.getProperty("user.home") + "\\AppData\\Roaming\\Data\\LogEr.txt");
            if (!error.exists()){
                try {
                    error.createNewFile();
                } catch (IOException exe) {
                }
            }
                try{
                    PrintWriter pw = new PrintWriter (error);
                    pw.print(e.getMessage());
                    pw.println();
                    pw.close();
                } catch (IOException exe){
                }
        }
    }
    private void irArriba(){
        //Método ejecutado por el Botón de ir arriba
        JViewport v = jScrollPane1.getViewport();
        Point p = v.getViewPosition();
        p.setLocation(0, 0);
        v.setViewPosition(p);
        jScrollPane1.setViewport(v);
    }
    private void comprobarKey() {
        //Escáner del teclado que comprueba si se ejecuta el huevo de pascua
        if (CHLG.equalsIgnoreCase(egg.toString())){
            jButton3.setVisible(true);
            jButton3.setBorderPainted(true);
            jButton3.setContentAreaFilled(true);
            jButton3.setEnabled(true);
            modify();
        }
    }
    private void modify(){
        //Método de huevo de pascua que permite la edición del ChangeLog
        if (jTextArea1.isEditable()){
            try{
                PrintWriter pw = new PrintWriter (new File (System.getProperty("user.home") + "\\AppData\\Roaming\\.minecraft\\mods\\CHLog.txt"));
                String temp = jTextArea1.getText();
                String [] splitter = temp.split("\n");
                for (int i = 0; i < splitter.length; i++){
                    pw.print(splitter[i]);
                    pw.println(); 
                }
                pw.close();
            } catch (IOException ex){
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        } else{
            jTextArea1.setEditable(true);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(5);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setTabSize(0);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextArea1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ir arriba");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Modificar");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(43, 43, 43)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton1)))
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //Botón aceptar
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //Botón Ir arriba
        irArriba();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextArea1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyPressed
        // TODO add your handling code here:
        //Escáner de teclado del Texto
        switch (evt.getKeyCode()){
            case KeyEvent.VK_A: egg.append("A");
            if(CHLG.length() == egg.length()){
                comprobarKey();
                egg.delete(0, egg.length());
            }
                break;
            case KeyEvent.VK_D: egg.append("D");
            if(CHLG.length() == egg.length()){
                comprobarKey();
                egg.delete(0, egg.length());
            }
            break;
            case KeyEvent.VK_M: egg.append("M");
            if(CHLG.length() == egg.length()){
                comprobarKey();
                egg.delete(0, egg.length());
            }
                break;
            case KeyEvent.VK_I: egg.append("I");
            if(CHLG.length() == egg.length()){
                comprobarKey();
                egg.delete(0, egg.length());
            }
                break;
            case KeyEvent.VK_N: egg.append("N");
            if(CHLG.length() == egg.length()){
                comprobarKey();
                egg.delete(0, egg.length());
            }
                break;
            case KeyEvent.VK_ENTER: modify();
                break;
        }
    }//GEN-LAST:event_jTextArea1KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //Botón de modificar
        modify();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Changelog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Changelog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Changelog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Changelog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Changelog dialog = new Changelog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
