

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.*;
import javax.swing.JOptionPane;
import java.util.*;
/**
 *
 * @author Reed
 */
public class PassConfirm extends javax.swing.JDialog {
    private String p;
    /**
     * Creates new form PassConfirm
     */
    public PassConfirm(java.awt.Frame parent, boolean modal, String pass) {
        super(parent, modal);
        initComponents();
        p = pass;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Nueva contraseña:");

        jLabel2.setText("Confirmar contraseña:");

        jLabel3.setText("Palabra secreta:");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPasswordField1)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //Botón de aceptar
        boolean change = false;
        try{
            BufferedReader bf = new BufferedReader(new FileReader (new File (System.getProperty("user.home") + "\\AppData\\Roaming\\Data\\data.cfg")));
            String temp = null, temp1 = null;
            temp = bf.readLine();
            temp = bf.readLine();
            //Nos quitamos de encima el nombre de usuario y la contraseña y vamos directamente a la palabra secreta
            StringECP crypt = new StringECP(p);
            temp1 = bf.readLine();
            temp = crypt.decrypt(temp1);
            //Desencriptamos la palabra y comprobamos si es la escrita en el área de texto
            if(temp.equals(jTextField1.getText())){
                change = true;
            }
            bf.close();
            if (change){
                //Si es la misma, comprobamos que la contraseña coincide
                String pass1 = new String (jPasswordField1.getPassword()), pass2 = new String (jPasswordField2.getPassword());
                if (pass1.equals(pass2)){
                    //Si coincide, obtenemos el nombre de usuario y lo desencriptamos
                    bf = new BufferedReader (new FileReader (new File(System.getProperty("user.home") + "\\AppData\\Roaming\\Data\\data.cfg")));
                    String tem = bf.readLine();
                    if (tem != null){
                    String user = crypt.decrypt(tem);
                    //Escribimos de nuevo el nombre de usuario, la nueva contraseña y la palabra secreta en el fichero de datos
                    PrintWriter pw = new PrintWriter(new File(System.getProperty("user.home") + "\\AppData\\Roaming\\Data\\data.cfg"));
                    pw.print(crypt.encrypt(user));
                    pw.println();
                    pw.print(crypt.encrypt(pass1));
                    pw.println();
                    pw.print(crypt.encrypt(temp));
                    pw.close();
                    JOptionPane.showMessageDialog(null, "La contraseña ha sido cambiada satisfactoriamente. Recuerda tu contraseña siempre.");
                    } else{
                        JOptionPane.showMessageDialog(null, "Eres usuario oficial de Minecraft o Mineshafter, no puedes cambiar tu contraseña desde aquí.");
                    }
                    bf.close();
                    this.dispose();
                } else{
                    JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden.");
                }
            } else{
                JOptionPane.showMessageDialog(null, "La palabra secreta no es correcta.");
            }
        } catch (IOException e){
            JOptionPane.showMessageDialog(null, "Error en el cambio de contraseña.");
            File error = new File (System.getProperty("user.home") + "\\AppData\\Roaming\\Data\\LogEr.txt");
            if (!error.exists()){
                try {
                    error.createNewFile();
                } catch (IOException exe) {
                }
            }
                try{
                    PrintWriter pw = new PrintWriter (error);
                    pw.print(e.getMessage());
                    pw.println();
                    pw.close();
                } catch (IOException exe){
                }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(final String args) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PassConfirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PassConfirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PassConfirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PassConfirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                PassConfirm dialog = new PassConfirm(new javax.swing.JFrame(), true, args);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
